import "~/styles/globals.css";
import { Inter } from "next/font/google";
import { Toaster } from "@components/toaster";
import { TRPCReactProvider } from "~/trpc/react";
import Head from "next/head";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Heartbeat",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/icon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  //TODO default is dark now we can add toggle support if we want
  return (
    <html lang="en" className="dark bg-background">
      <Head>
        <link rel="icon" type="image/x-icon" href="/icon.ico"></link>
      </Head>
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider>{children}</TRPCReactProvider>
        <Toaster />
      </body>
    </html>
  );
}
