name: Deploy and Test with Vercel and Playwright

on:

  push:

    branches:

      - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - uses: vercel/action@v20

        with:

          vercel_token: ${{ secrets.VERCEL_TOKEN }}

          vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}

          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}

  test:

    needs: deploy

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Install dependencies

        run: npm install

      - name: Run Playwright tests

        run: npx playwright test